### PR TITLE
Fix undefined index 'splits'

### PR DESCRIPTION
**Pull request by yceruto**
See https://travis-ci.org/symfony/symfony/jobs/557427277#L2601

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
When does this happen?

**Comment by yceruto** [comment]
Maybe because https://github.com/symfony/flex/issues/527#issuecomment-510220086 ?

**Comment by yceruto** [comment]
Although it shouldn't happen, it's always present at https://flex.symfony.com/versions.json, isn't it?

Maybe a download error from Travis because AppVeyor don't have this issue.

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/symfony/flex/pull/538

**Pull request closed without merging**
