### PR TITLE
Add compatibility with composer-plugin-api ^1.0

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Let's remove this friction point, especially when Ubuntu's Composer is v1.0.2. Will save a few blocking steps for new comers.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
PR ready - all features except "unpack" work on 1.0. A warning is displayed when an old version of composer is used.

image

or 

image

**Comment by javiereguiluz** [comment]
Could we display that warning message only when the user tries to execute an unsupported feature?

**Comment by nicolas-grekas** [comment]
We cannot : if we were able to hook there, we would be able to implement the unsupported features :)

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
