### PR TITLE
use the composer command event to hide suggest messages

### PR DESCRIPTION
**Pull request by prisis**
If you set the composer min version to v1.2 you can use the command event to hide the suggest messages

### CODE REVIEW

**Comment by Pierstoval** [comment]
What is the real reason to hide the suggest messages?

**Comment by nicolas-grekas** [comment]
@Pierstoval the message is already hidden, nothing new on the topic here, that's part of the "Flex experience", to give space to recipes.

@prisis Flex works also with older composer versions, will break them?

**Comment by prisis** [comment]
Yes, this isn't a breaking change.

This will only work if the user has a composer version bigger then v1.2

**Comment by maxhelias** [comment]
So with your PR, is the condition here is always necessary ?
https://github.com/symfony/flex/blob/master/src/Flex.php#L170

**Comment by prisis** [comment]
Thx, missed that one, I will change that before the pr will be merged

**Comment by fabpot** [comment]
Thanks for the PR, but the current was written to explicitly support old versions of Composer.

**Pull request closed without merging**
