### PR TITLE
Implement package.json synchronization

### PR DESCRIPTION
**Pull request by tgalopin**
Implement package.json synchronization for Symfony UX

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @tgalopin.

**Comment by apfelbox** [comment]
Ar there any docs about this feature?

**Comment by tgalopin** [comment]
Not yet, because Symfony UX is still a bit early. You can find details in the talks of Fabien and me at the SymfonyWorld online (live.symfony.com) or on the blog (https://symfony.com/blog/new-in-symfony-the-ux-initiative-a-new-javascript-ecosystem-for-symfony). You can also ping me on the Symfony Devs Slack, in the ux channel :).

**Comment by apfelbox** [comment]
Thanks for the response @tgalopin !
I am mainly interested in how the synchronization works and where I need to put my package names, that should be automatically added to the main `package.json`

**Comment by tgalopin** [comment]
Let's discuss on Slack, much easier :) : https://symfony.com/slack

**Pull request merged**
