### PR TITLE
Use \n instead of PHP_EOL

### PR DESCRIPTION
**Pull request by dunglas**
Using `PHP_EOL` may cause issues when some developers use Windows while others use UNIX. I propose to follow the UNIX convention.

Still a WIP.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
In my opinion this proposal is technically wrong. `PHP_EOL` is the only correct value for every user (Windows, Linux, macOS). The case you mentioned (a team where some people use Windows and others use Linux/macOS) is and edged-case that I don't think we should solve ourselves (that team should be careful when configuring their editors ... not only for Flex, but for Symfony, PHP and any other file types).

**Comment by dunglas** [comment]
> that team should be careful when configuring their editors

It's exactly what this PR fixes. The generated files are not created through editors but created by Flex.

**Comment by lyrixx** [comment]
I agree with @dunglas here.
More over, in [my git config](https://github.com/lyrixx/dotfiles/blob/master/.gitconfig#L41), git automatically transform all `\r\n` to `\n`.
So using only `\n` will avoid useless commit ;)

**Comment by javiereguiluz** [comment]
@lyrixx your Git configuration is correct ... but we cannot assume the same for other developers.

In any case, to me this PR is obviously wrong ... but for you is obviously right ... so someone must be incredibly wrong ... and I guess it's me 😞

**Comment by stof** [comment]
👍 about using Unix line ending when generating files, as these files are meant to be committed.

**Comment by stof** [comment]
Btw, a .env file with Windows line endings cannot be sourced anymore when using bash, as bash supports only LF line-endings in bash files (even when compiling bash for windows)

**Comment by Pierstoval** [comment]
For the makefile, I could not make it work on Windows with `\n` nor `\r\n`, because it uses unix-based commands (like `test` for example), so needs Linux (WSL or at least unix commands in Path).

I'm 👍 for this change for consistency anyway, especially for `.env` file

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
