### PR TITLE
Alphabetize bundles by key

### PR DESCRIPTION
**Pull request by ericpoe**
This helps organize bundles by vendor and bundle family. This is for UX and has no bearing on the performance of the application.

As an example, after setting up an initial skeleton project, I wanted to install api-platform, but since the default "minimum-stability" of skeleton is "stable" instead of "dev," a quick `composer req api` fails. So, I installed all of the libraries and bundles in https://github.com/api-platform/api-pack/blob/master/composer.json, then I ran `composer require admin` for added complexity. I took a look at my `bundles.php` and saw this:

```php
return [
    'Symfony\Bundle\FrameworkBundle\FrameworkBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineBundle\DoctrineBundle' => ['all' => true],
    'Symfony\Bundle\SecurityBundle\SecurityBundle' => ['all' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle' => ['all' => true],
    'Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle' => ['all' => true],
    'JavierEguiluz\Bundle\EasyAdminBundle\EasyAdminBundle' => ['all' => true],
];
```

The bundles appear to be randomly sorted and I have a harder time quickly grokking which bundles are installed. Wouldn't it be nice to see all of these bundles arranged alphabetically so that I can see them grouped by vendor and maybe library family? Perhaps, something like this:

```php
return [
    'Doctrine\Bundle\DoctrineBundle\DoctrineBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' => ['all' => true],
    'JavierEguiluz\Bundle\EasyAdminBundle\EasyAdminBundle' => ['all' => true],
    'Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle' => ['all' => true],
    'Symfony\Bundle\FrameworkBundle\FrameworkBundle' => ['all' => true],
    'Symfony\Bundle\SecurityBundle\SecurityBundle' => ['all' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle' => ['all' => true],
];
```
As can be seen above, I can quickly tell that I have 2 Doctrine bundles, 3 Symfony bundles, a JavierEguiluz bundle, and a Sensio bundle. In the first example, I cannot quickly discern which bundles I have.

Imagine what this will look like once more and more bundles are added!

### CODE REVIEW

**Comment by fabpot** [comment]
I'm mostly 👎 , but in any case, frameworkbundle should stay first.

**Comment by ericpoe** [comment]
For my education, why should frameworkbundle stay first? Composer is already alphabetizing all requirements, why not `$bundles`?

**Comment by Pierstoval** [comment]
Composer requirements and bundles are different. Requirements are just here to define project's dependencies, and they're managed by Composer, the order doesn't matter at all.

With bundles, it's different. The kernel retrieves the list of bundles, and then `Kernel::boot()` will initialize bundles with a simple `foreach` loop, therefore processing them one after the other, like, procedurally. Same for bundle extensions and compiler passes. So to avoid any strange complication, it's better to keep FrameworkBundle at the top, and let the user change the order manually IMO.

**Comment by ericpoe** [comment]
@Pierstoval I appreciate the excellent answer to my poorly worded question.

**Pull request closed without merging**
