### PR TITLE
Fork Interval classes from composer/semver

### PR DESCRIPTION
**Pull request by nicolas-grekas**
This is a copy/paste from https://github.com/composer/semver/ v3.

We're going to need this logic to implement #645

Forking is required because composer/semver v3 is shipped with Composer 2 but not with Composer 1.

/cc @Seldaek FYI

### CODE REVIEW

**Comment by Seldaek** [comment]
Obviously you're free to do this but IMO it might be better to make the new functionality composer 2 only than copy paste all this code. Up to you.

**Comment by stof** [comment]
why do you need this logic to implement #645 ?

**Comment by nicolas-grekas** [comment]
We'll need this logic when we'll want to merge version constraints to support anything else than `*`, or to support `conflict`/`replace`.

I don't think we can bind this to Composer 2. The behavior on Composer 1 would have to be defined anyway and there is no other appropriate behavior.

**Comment by nicolas-grekas** [comment]
Closing because I'm not going to need this I think.
Could be reopened if needed.

**Pull request closed without merging**
