### PR TITLE
Make Flex work on PHP 7.0

### PR DESCRIPTION
**Pull request by nicolas-grekas**
IMHO, enforcing 7.1 is only slowing down the adoption of Flex.
Unlike other existing projects that can tell "use the previous existing version",
we're starting with no community at all, and we want to spread adoption.
This is a strategic move to me.

Symfony 3.4 does work with 7.0, so PHP 7.0 users/companies that want to start new projects on it will have the choice to start with an already outdated standard edition, or nothing. This may hurt the Symfony project.

We have to provide a better alternative to them: Flex on PHP 7.0.
Here it is.

### CODE REVIEW

**Comment by B-Galati** [comment]
I think it's a good idea but @fabpot did a poll on Twitter on this and 7.1 won. So perhaps this change is not gonna be welcome by the community.
Here is the tweet -> https://twitter.com/fabpot/status/851558576770252800
Also, the active support of php 7.0 ends in December.

**Comment by nicolas-grekas** [comment]
@B-Galati the pool was about Symfony 4, it doesn't apply to Flex IMHO. I see no reasons why it should.

**Comment by B-Galati** [comment]
Good point ! You are entirely right 👍

**Comment by stof** [comment]
Well, PHP 7.0 will reach end of active support on December 3rd.

Flex is expected to be released syable at the same time than Symfony 3.4 and 4.0, which means on November 30th.

Do we actually need to reintroduce support for PHP 7.0 for 3 days of active support ?

**Comment by stof** [comment]
btw, if you want to add PHP 7.0 support, it does not only involves changing Flex itself, but also reviewing all recipes to ensure they are compatible with PHP 7.0 (hint: currently, they are not)

**Comment by stof** [comment]
And currently, we don't have a way to make Flex select an older version of a recipe based on the targeted PHP version, so we would never be able to use PHP 7.1 features in recipe codes unless the targeted version of the composer package requires PHP 7.1+, meaning we would have to start a new version of the recipe for Symfony 4.0 packages.

And the first package recipe I know of requiring PHP 7.1 is `symfony/framework-bundle`

**Comment by fabpot** [comment]
@nicolas-grekas That's for you :)

**Comment by nicolas-grekas** [comment]
Where in FrameworkBundle? I parses all PHP files, they all are ok with 7.0 now.

**Comment by nicolas-grekas** [comment]
We don't have a way to select a recipe based in a PHP version, but I'd expect a recipe to match the min version of the package version they configure. So that's not a real issue to me.

**Comment by stof** [comment]
@nicolas-grekas whihc is not the case currently, as they were written with the assumption that Flex itself targets PHP 7.1, and so `max(PHP 7.1, min-package-target)` was used as recipe supported version. So **all** recipes must be reviewed.

**Comment by nicolas-grekas** [comment]
No pb, there are only very few PHP files in the repos, I'll take care of it.

**Comment by stof** [comment]
@nicolas-grekas don't forget the contrib ones

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/recipes/pull/195

**Comment by nicolas-grekas** [comment]
> PHP 7.0 will reach end of active support on December 3rd

PHP 7.0 will reach end of life on 3 Dec 2018, and even later if we consider Ubuntu Xenial, which will maintain it until April 2021. So definitely yes, we want to support 7.0.

**Comment by fabpot** [comment]
@nicolas-grekas You should probably change the min version in symfony/skeleton as well, right?

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Pull request merged**
