### PR TITLE
Fix bad wiring of repository manager

### LINKED ISSUE #381: ParallelDownloader suddenly crashes (v1.0.81)
To reproduce:

```
composer create-project symfony/skeleton foo && cd foo && composer require orm
```

Result:

```
Installing symfony/skeleton (v4.1.0)
  - Installing symfony/skeleton (v4.1.0): Downloading (100%)         
Created project in foo
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.81): Downloading (100%)         

Prefetching 20 packages 🎶
  - Downloading (100%)

  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing symfony/console (v4.1.1): Loading from cache
  - Installing symfony/routing (v4.1.1): Loading from cache
  - Installing symfony/yaml (v4.1.1): Loading from cache
  - Installing symfony/framework-bundle (v4.1.1): Loading from cache
  - Installing symfony/http-kernel (v4.1.1): Loading from cache
  - Installing symfony/http-foundation (v4.1.1): Loading from cache
  - Installing symfony/event-dispatcher (v4.1.1): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.1.1): Loading from cache
  - Installing symfony/finder (v4.1.1): Loading from cache
  - Installing symfony/filesystem (v4.1.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.1.1): Loading from cache
  - Installing symfony/config (v4.1.1): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.1.1): Loading from cache
  - Installing symfony/dotenv (v4.1.1): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 4 recipes (04c4a9fa1a98c2ae2e3cb3994af56bd7)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
  - Configuring symfony/framework-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=4.0): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

              
 What's next? 
              

  * Run your application:
    1. Change to the project directory
    2. Create your code repository with the git init command
    3. Execute the php -S 127.0.0.1:8000 -t public command
    4. Browse to the http://localhost:8000/ URL.

       Quit the server with CTRL-C.
       Run composer require server --dev for a better web server.

  * Read the documentation at https://symfony.com/doc

/app/foo
Using version ^1.0 for symfony/orm-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Uncaught Error: Function name must be a string in /app/vendor/symfony/flex/src/ParallelDownloader.php:246
Stack trace:
#0 /app/vendor/symfony/flex/src/ParallelDownloader.php(84): Symfony\Flex\ParallelDownloader->getNext()
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(452): Symfony\Flex\ParallelDownloader->download(Array, Object(Closure))
#2 [internal function]: Symfony\Flex\Flex_composer_tmp0->populateProvidersCacheDir(Object(Composer\Installer\InstallerEvent))
#3 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Installer\InstallerEvent))
#4 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(135): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\InstallerEvent))
#5 phar:///usr/bin/composer/src/Composer/Installer.php(470): Composer\EventDispatcher\EventDispatcher->dispatchInstallerEvent('pre-dependencie...', true, Object(Composer\DependencyResolver\D in /app/vendor/symfony/flex/src/ParallelDownloader.php on line 246
```

### LINKED ISSUE #382: Repository type is not registered - v1.0.81
The latest release seems to break [custom repositories](https://getcomposer.org/doc/05-repositories.md#vcs) feature in `composer.json`.

Step to reproduce:

Add this in your `composer.json`: 
```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/0x46616c6b/monolog"
        }
    ],
```

Then run `composer update`.

Expected result: the update run properly

Actual result: 
```
Loading composer repositories with package information                                                                                                                         Updating dependencies (including require-dev)         
Package operations: 74 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.81): Loading from cache
Plugin installation failed, rolling back
  - Removing symfony/flex (v1.0.81)

                                          
  [InvalidArgumentException]              
  Repository type is not registered: vcs  
```

The update works fine if I manually set `symfony/flex` to v1.0.80.

composer v1.6.5
PHP 7.2.7

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fixes #381
Fixes #382 
Replaces #384

### CODE REVIEW

**Comment by fabpot** [comment]
Anyone willing to test this patch before I merge it and release a new version? /cc @ro0NL @sstok @renanbr @lpj145 @andre-qup  @hotrush

**Comment by ro0NL** [comment]
Works for me :+1:

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

**Comment by stof** [comment]
@nicolas-grekas wouldn't this stop downloading files in parallel from Packagist, making the parallel ComposerRepository useless ?

**Comment by nicolas-grekas** [comment]
Just checked: parallel downloads aren't hooked into the repository manager and they work because things happens by prefetching.

**Pull request merged**
