### PR TITLE
Don't remove the main Git directory

### PR DESCRIPTION
**Pull request by javiereguiluz**
This is an attempt to fix https://github.com/symfony/recipes/issues/324  but I haven't tested it properly yet!

### CODE REVIEW

**Comment by xabbuh** [comment]
What about doing this one level higher by just not allowing to remove the recipe applied for `symfony/flex`?

**Comment by nicolas-grekas** [comment]
LGTM for @xabbuh's proposal.

**Comment by nicolas-grekas** [comment]
But then some of FrameworkBundle's gitignore should be moved to the flex recipe (.env and vendor), isn't it?

**Comment by weaverryan** [comment]
I prefer the *current* patch over @xabbuh's proposal, actually. It makes more sense to me to day "`.git` is special, don't remove it" versus "the entire symfony/flex recipe is special, don't remove it". 

👍 for the PR as it is currently

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request merged**
