### PR TITLE
Ignore existing env vars when running dump-env

### LINKED ISSUE #475: Flex 1.2 / dump-env command and existing environment variables
Hi,

```
$ cat .env|wc -l
101

$ composer dump-env dev && cat .env.local.php 
Successfully dumped .env files in .env.local.php
<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
);
```

In the execution context of the `composer dump-env dev` command, all my env variables in my `.env` file are in fact already sourced (already present as env variables).

I would expect the `dump-env` command to not be impacted by what variables are already set in the env  and just dump whatever is in `.env*` to `.env.local.php`. Otherwise it leads to unexpected results (empty or partial env cache file generated).

Is that my mistake to have such env variables already sourced or is it an unexpected behavior of `dump-env`, or both ?

Thanks!

### LINKED ISSUE #476: Loading values from `.env.local.php` is not equivalent to `DotEnv::loadEnv`
Hi,

It seems that `composer dump-env` is not equivalent to `DotEnv::loadEnv` loading yaml files.

Please see this repository for a reproducer and the README for a description of the problem.
https://github.com/bendavies/symfony-flex-env-issue

Thanks

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fix #475
Fix #476
Fix https://github.com/symfony/symfony/pull/30418

### CODE REVIEW

**Comment by bendavies** [comment]
didn't get a notification for this on my linked issue. thanks - i'll take a look.

**Comment by DavG** [comment]
This introduces bug #500 

```
foreach ($_SERVER as $k => $v) {
    if (\is_string($v) && false !== getenv($k)) {
        unset($_SERVER[$k]);
        putenv($k);
    }
}
```

**Comment by bendavies** [comment]
@nicolas-grekas I thought I checked but it doesn't not seem that this fixed the issue described at https://github.com/symfony/flex/issues/476. https://github.com/bendavies/symfony-flex-env-issue is still an issue.

**Comment by bendavies** [comment]
looking at the fix in this PR, I cant see the issue was resolved actually. the problem was not with `dump-env`, but with the loading of var in `bootstrap.php`

**Pull request merged**
