### PR TITLE
Add help command and set it by default

### PR DESCRIPTION
**Pull request by Grafikart**
This is a very opinionated PR so be free to close it if you don't like it.

When `make` is used without argument it will print an help showing available targets for the current project (`make help` can also be used). The output is based on this [post](https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html) but can be simplified.

csgrxlf

To use this feature "recipes" will have to comment public targets, for instance :

```makefile
cache-clear: ## Clear the cache
ifdef CONSOLE
	@$(CONSOLE) cache:clear --no-warmup
else
	@rm -rf var/cache/*
endif
```

Targets that are not commented are not visible (usefull to "hide" target used internaly like `serve_as_php` or `serve_as_symfony`)

### CODE REVIEW

**Comment by sstok** [comment]
Target with underscores should be ignored as these are considered internal.

**Comment by Grafikart** [comment]
If you don't comment the target it won't appear, but I fixed the regexp to ignore _

**Comment by Nicofuma** [comment]
With `@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m##/[33m/'` you can add sections and you will also have colors close to the bin/console ones.

Ex with sections:
```
#
## Section 1
##---------------------------------------------------------------------------

target1:          ## target one

#
## Section 2
##---------------------------------------------------------------------------

target2:          ## target two
target2: target1
```

**Comment by fabpot** [comment]
Thank you @Grafikart.

**Comment by fabpot** [comment]
see symfony/recipes#207

**Pull request closed without merging**
