### PR TITLE
Fixing duplicate Cache error

### LINKED ISSUE #388: Cache namespace is already in use
Since v1.0.83, a new file Cache.php was added in src/
This file cause an error in Download.php beacuse it uses  (line 14):
use Composer\Cache;
which causes an error because "Cache" already exists in this namespace (because of that new file)
Can you fix this ?

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #388

### CODE REVIEW

**Comment by maxhelias** [comment]
I think we should instead use the `Cache` defined in Flex because it extends from `Composer\Cache`.
Just delete line 14 should be enough in my opinion

**Comment by nicolas-grekas** [comment]
@maxhelias Cache in the flex namespace has a different responsibility, we should really use Composer's here.

**Comment by fabpot** [comment]
Thank you @weaverryan.

**Pull request merged**
